//
//  ManageBabyNamesInteractor.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 7/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ManageBabyNamesInteractorInput
{
  func doSomething(request: ManageBabyNamesRequest)
}

protocol ManageBabyNamesInteractorOutput
{
  func presentSomething(response: ManageBabyNamesResponse)
}

class ManageBabyNamesInteractor: ManageBabyNamesInteractorInput
{
  var output: ManageBabyNamesInteractorOutput!
  var worker: ManageBabyNamesWorker!
  
  // MARK: Business logic
  
  func doSomething(request: ManageBabyNamesRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ManageBabyNamesWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ManageBabyNamesResponse()
    output.presentSomething(response)
  }
}
