//
//  ManageBabyNamesPresenter.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 7/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ManageBabyNamesPresenterInput
{
  func presentSomething(response: ManageBabyNamesResponse)
}

protocol ManageBabyNamesPresenterOutput: class
{
  func displaySomething(viewModel: ManageBabyNamesViewModel)
}

class ManageBabyNamesPresenter: ManageBabyNamesPresenterInput
{
  weak var output: ManageBabyNamesPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentSomething(response: ManageBabyNamesResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ManageBabyNamesViewModel()
    output.displaySomething(viewModel)
  }
}
