//
//  ManageBabyNamesViewController.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 7/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ManageBabyNamesViewControllerInput
{
  func displaySomething(viewModel: ManageBabyNamesViewModel)
}

protocol ManageBabyNamesViewControllerOutput
{
  func doSomething(request: ManageBabyNamesRequest)
}

class ManageBabyNamesViewController: UIViewController, ManageBabyNamesViewControllerInput
{
  var output: ManageBabyNamesViewControllerOutput!
  var router: ManageBabyNamesRouter!
  
  // MARK: Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    ManageBabyNamesConfigurator.sharedInstance.configure(self)
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: Event handling
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = ManageBabyNamesRequest()
    output.doSomething(request)
  }
  
  // MARK: Display logic
  
  func displaySomething(viewModel: ManageBabyNamesViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
