//
//  RetrieveBabyNamesModels.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 7/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct RetrieveBabyNamesRequest
{
}

struct RetrieveBabyNamesResponse
{
}

struct RetrieveBabyNamesViewModel
{
}
