//
//  RetrieveBabyNamesViewController.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 7/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol RetrieveBabyNamesViewControllerInput
{
  func displaySomething(viewModel: RetrieveBabyNamesViewModel)
}

protocol RetrieveBabyNamesViewControllerOutput
{
  func doSomething(request: RetrieveBabyNamesRequest)
}

class RetrieveBabyNamesViewController: UIViewController, RetrieveBabyNamesViewControllerInput
{
  var output: RetrieveBabyNamesViewControllerOutput!
  var router: RetrieveBabyNamesRouter!
  
  // MARK: Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    RetrieveBabyNamesConfigurator.sharedInstance.configure(self)
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: Event handling
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = RetrieveBabyNamesRequest()
    output.doSomething(request)
  }
  
  // MARK: Display logic
  
  func displaySomething(viewModel: RetrieveBabyNamesViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
