//
//  RetrieveBabyNamesConfigurator.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 7/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension RetrieveBabyNamesViewController: RetrieveBabyNamesPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension RetrieveBabyNamesInteractor: RetrieveBabyNamesViewControllerOutput
{
}

extension RetrieveBabyNamesPresenter: RetrieveBabyNamesInteractorOutput
{
}

class RetrieveBabyNamesConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: RetrieveBabyNamesConfigurator
  {
    struct Static {
      static var instance: RetrieveBabyNamesConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = RetrieveBabyNamesConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: RetrieveBabyNamesViewController)
  {
    let router = RetrieveBabyNamesRouter()
    router.viewController = viewController
    
    let presenter = RetrieveBabyNamesPresenter()
    presenter.output = viewController
    
    let interactor = RetrieveBabyNamesInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
