//
//  RetrieveBabyNamesInteractor.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 7/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol RetrieveBabyNamesInteractorInput
{
  func doSomething(request: RetrieveBabyNamesRequest)
}

protocol RetrieveBabyNamesInteractorOutput
{
  func presentSomething(response: RetrieveBabyNamesResponse)
}

class RetrieveBabyNamesInteractor: RetrieveBabyNamesInteractorInput
{
  var output: RetrieveBabyNamesInteractorOutput!
  var worker: RetrieveBabyNamesWorker!
  
  // MARK: Business logic
  
  func doSomething(request: RetrieveBabyNamesRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = RetrieveBabyNamesWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = RetrieveBabyNamesResponse()
    output.presentSomething(response)
  }
}
