//
//  ShowBabyNamesConfigurator.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 9/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ShowBabyNamesViewController: ShowBabyNamesPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension ShowBabyNamesInteractor: ShowBabyNamesViewControllerOutput
{
}

extension ShowBabyNamesPresenter: ShowBabyNamesInteractorOutput
{
}

class ShowBabyNamesConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: ShowBabyNamesConfigurator
  {
    struct Static {
      static var instance: ShowBabyNamesConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = ShowBabyNamesConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: ShowBabyNamesViewController)
  {
    let router = ShowBabyNamesRouter()
    router.viewController = viewController
    
    let presenter = ShowBabyNamesPresenter()
    presenter.output = viewController
    
    let interactor = ShowBabyNamesInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
