//
//  ShowBabyNamesInteractor.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 9/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowBabyNamesInteractorInput
{
  func doSomething(request: ShowBabyNamesRequest)
}

protocol ShowBabyNamesInteractorOutput
{
  func presentSomething(response: ShowBabyNamesResponse)
}

class ShowBabyNamesInteractor: ShowBabyNamesInteractorInput
{
  var output: ShowBabyNamesInteractorOutput!
  var genericRepo: GenericRepository!
  
  // MARK: Business logic
  
  func doSomething(request: ShowBabyNamesRequest)
  {
    // NOTE: Create some Worker to do the work
    
    genericRepo = GenericRepository()
    genericRepo.fetchBabyNames({ (_babyNames, _error) in
        let response = ShowBabyNamesResponse(babyNames: _babyNames, error: _error)
        self.output.presentSomething(response)
    })
    
    // NOTE: Pass the result to the Presenter
    
    
  }
}
