//
//  ShowBabyNamesPresenter.swift
//  BabyNamesv2
//
//  Created by Felipe Caldas on 9/02/2016.
//  Copyright (c) 2016 FunkApps FMC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowBabyNamesPresenterInput
{
  func presentSomething(response: ShowBabyNamesResponse)
}

protocol ShowBabyNamesPresenterOutput: class
{
  func displaySomething(viewModel: ShowBabyNamesViewModel)
}

class ShowBabyNamesPresenter: ShowBabyNamesPresenterInput
{
  weak var output: ShowBabyNamesPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentSomething(response: ShowBabyNamesResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    if response.error != nil {
        let viewModel = ShowBabyNamesViewModel(nameList: "Error retrieving Baby Names")
        output.displaySomething(viewModel)
    } else {
        var result = ""
        for var i = 0; i < 5; i++ {
            result += response.babyNames![i].name! + "; "
        }
        let viewModel = ShowBabyNamesViewModel(nameList: result)
        output.displaySomething(viewModel)
    }
  }
}
